package com.teachy.backend.common.enums;

public enum QuestionType {
    MATCHING_HEADINGS, TRUE_FALSE_NOTGIVEN, YES_NO_NOTGIVEN, MCQ,
    MATCHING_INFORMATION, MATCHING_FEATURES, MATCHING_SENTENCE_ENDINGS,
    SENTENCE_COMPLETION, SUMMARY_COMPLETION, TABLE_COMPLETION,
    FLOWCHART_COMPLETION, DIAGRAM_LABEL_COMPLETION, SHORT
}
