-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('LEARNER', 'INSTRUCTOR', 'ADMIN');

-- CreateEnum
CREATE TYPE "CefrLevel" AS ENUM ('A2', 'B1', 'B2', 'C1');

-- CreateEnum
CREATE TYPE "ContentStatus" AS ENUM ('DRAFT', 'PUBLISHED');

-- CreateEnum
CREATE TYPE "QuestionType" AS ENUM ('MATCHING_HEADINGS', 'TRUE_FALSE_NOTGIVEN', 'YES_NO_NOTGIVEN', 'MCQ', 'MATCHING_INFORMATION', 'MATCHING_FEATURES', 'MATCHING_SENTENCE_ENDINGS', 'SENTENCE_COMPLETION', 'SUMMARY_COMPLETION', 'TABLE_COMPLETION', 'FLOWCHART_COMPLETION', 'DIAGRAM_LABEL_COMPLETION', 'SHORT');

-- CreateEnum
CREATE TYPE "TaskType" AS ENUM ('TASK1', 'TASK2');

-- CreateEnum
CREATE TYPE "ModelTier" AS ENUM ('CHEAP', 'PREMIUM');

-- CreateEnum
CREATE TYPE "ProcessingStatus" AS ENUM ('PENDING', 'DONE', 'FAILED');

-- CreateEnum
CREATE TYPE "ClassroomStatus" AS ENUM ('ACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "ClassroomRole" AS ENUM ('TEACHER', 'STUDENT');

-- CreateEnum
CREATE TYPE "LessonContentType" AS ENUM ('TEXT', 'VIDEO', 'PASSAGE', 'PROMPT');

-- CreateEnum
CREATE TYPE "SubmissionState" AS ENUM ('DRAFT', 'SUBMITTED', 'AI_SCORED', 'AI_FAILED', 'RELEASED_AI', 'PENDING_REVIEW', 'FINALIZED');

-- CreateEnum
CREATE TYPE "WritingMode" AS ENUM ('INSTANT', 'REVIEW_FIRST');
